image: node:latest
cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - npm install
    - npm i -g firebase-tools
    - npm run build
    - firebase deploy --non-interactive --only hosting --token
    "1/WdqkGnHMwWXyN0ZqYPWMvxjzi0DzhfjTmsmav4xLXkA"