image: node:latest

variables:
  FIREBASE_DEPLOY_KEY: "1/WdqkGnHMwWXyN0ZqYPWMvxjzi0DzhfjTmsmav4xLXkA"

stages:
  - develop

before_script:
  - npm -g config set user root
  - npm install -g firebase-tools
  - npm install

cache:
  paths:
    - node_modules/

staging:
  stage: develop
  environment: development
  only:
    - develop
  script:
    - npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY